language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
   - PACKAGE="dns"
   - DEPOPTS="tcpip lwt async"
   - REVDEPS="true"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_BUILD_HOOKS="./.travis-ci-post.sh"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03.0
   - DISTRO=debian-testing OCAML_VERSION=4.02.3
   - DISTRO=debian-unstable OCAML_VERSION=4.02.3
   - DISTRO=ubuntu-12.04 OCAML_VERSION=4.02.3
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=centos-6 OCAML_VERSION=4.02.3
   - DISTRO=centos-7 OCAML_VERSION=4.02.3
   - DISTRO=fedora-24 OCAML_VERSION=4.02.3
   - DISTRO=alpine-3.4 OCAML_VERSION=4.03.0
